name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-windows:
    needs: create-release
    uses: ./.github/workflows/build-windows.yml

  build-macos:
    needs: create-release
    uses: ./.github/workflows/build-macos.yml

  build-linux:
    needs: create-release
    uses: ./.github/workflows/build-linux.yml

  upload-release-assets:
    needs: [ build-windows, build-macos, build-linux ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List artifacts
        run: find . -type f -exec ls -lh {} \;

      - name: Upload assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/wiremann-*
            **/WiremannSetup_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}